POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hc2lxIiwiaWQiOiI2OTYyODExYjljZGZhNzdhMjFmNWU2N2YiLCJpYXQiOjE3NjgwNjM4OTR9.Z26Dghz0kPqqykNJwQgk_h5om6iZWBVjSfBJBav_dHQ

{
  "content": "This post requires token",
  "important": true
}
